require 'cancan-permits/namespaces'
require_all File.dirname(__FILE__) + '/permit'
require_all File.dirname(__FILE__) + '/role_permit'
require_all File.dirname(__FILE__) + '/role_group_permit'
require_all File.dirname(__FILE__) + '/permits'
require_all File.dirname(__FILE__) + '/license'
require_all File.dirname(__FILE__) + '/loader'
require_all File.dirname(__FILE__) + '/parser'
require_all File.dirname(__FILE__) + '/configuration'